### ISSUE TITLE
MSPLib and format

### ISSUE THREAD

**Issue by odow** [odow/StochOptFormat#22]
@bonnkleiford another option we didn't discuss: we could write a translator from MSPFormat to StochOptFormat. That might be even easier than writing a parser for SDDP.jl?

**Comment by bonnkleiford** [comment]
@odow hmmm. that is true. if it will be easier, I think it is an interesting angle to look into. I'll also bring it up to Nils.

**Comment by odow** [comment]
This is working, https://github.com/odow/SDDP.jl/pull/593, so I don't feel the need to write a converter. It's a little fiddly. We could look into it again if there is demand.
